baseurl = "/"
languageCode = "en-us"
title = "Davide Lorino"
theme = "hugo-lithium"
googleAnalytics = "UA-123002746-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "about"
    url = "/about/"
[[menu.main]]
    name = "github"
    url = "https://github.com/davelorino"
[[menu.main]]
    name = "contact"
    url = "davelorino@gmail.com"

[params]
    description = "Joy in Playing."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    [params.logo]
    url = "blackcat.png"
    width = 50
    height = 50
    alt = "Logo"

